### ISSUE TITLE
Missing netcdf files for sphinx-build

### ISSUE THREAD

**Issue by admg26** [pygeode/pygeode-docs#2]
Hi,

Just ran sphinx-build on this. I am missing the files sample_data/* 
`<ipython-input-18-2078fd414dca> in <module>()`
`----> 1 ds = pyg.open('sample_data/file.nc')`

A

**Comment by neishm** [comment]
I can reproduce the problem on my end as well.  I was able to fix this by making an empty `sample_data` directory in my local `pygeode-docs` repository.  I'll add this directory stub to the repository so this isn't a problem in the future.

**Comment by aph42** [comment]
Yeah - the code assumes this directory exists; all the data that get saved within it are generated by the tutorial scripts as sphinx builds the html files. Git doesn't allow for adding empty directories but we could add a dummy file in there.

**Comment by aph42** [comment]
Ah - as was done. That works.

**Comment by admg26** [comment]
Oh that is where the sample_data dir goes.
